### ISSUE TITLE
如何在ubuntu中使用 pinyin-emoji-input

### ISSUE THREAD

**Issue by nirvana6** [Nuclides/pinyin-emoji-input#3]
我使用的ubuntu15.04，无法执行 :
 `python3 generator.py /usr/share/mecabra/zh/common/emoji.plist` 

请问：如何在ubuntu的fcitx中使用您的插件？

**Comment by xhacker** [comment]
你要在 OS X 上执行这行命令。因为 `/usr/share/mecabra/zh/common/emoji.plist` 是 OS X 上提供的 emoji 数据。
